// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOzCXestvGj5dtnlURKzgROba26GxokOE',
    appId: '1:469339613473:web:656be9c4c76845bbfe3660',
    messagingSenderId: '469339613473',
    projectId: 'albertian-wellnest-6f3c5',
    authDomain: 'albertian-wellnest-6f3c5.firebaseapp.com',
    storageBucket: 'albertian-wellnest-6f3c5.firebasestorage.app',
    measurementId: 'G-EWWBMX6GYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxLopVgdDGONqNkxJhyBfMeRoC_TbETBQ',
    appId: '1:469339613473:android:402da3ce99d126ddfe3660',
    messagingSenderId: '469339613473',
    projectId: 'albertian-wellnest-6f3c5',
    storageBucket: 'albertian-wellnest-6f3c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpq1sUzgVsVTg_SXRNvfj6H85fI_3WiCE',
    appId: '1:469339613473:ios:79e74a095da0bd03fe3660',
    messagingSenderId: '469339613473',
    projectId: 'albertian-wellnest-6f3c5',
    storageBucket: 'albertian-wellnest-6f3c5.firebasestorage.app',
    iosBundleId: 'wellnest.com.albertianWellnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpq1sUzgVsVTg_SXRNvfj6H85fI_3WiCE',
    appId: '1:469339613473:ios:79e74a095da0bd03fe3660',
    messagingSenderId: '469339613473',
    projectId: 'albertian-wellnest-6f3c5',
    storageBucket: 'albertian-wellnest-6f3c5.firebasestorage.app',
    iosBundleId: 'wellnest.com.albertianWellnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOzCXestvGj5dtnlURKzgROba26GxokOE',
    appId: '1:469339613473:web:6b2877c24c2182aafe3660',
    messagingSenderId: '469339613473',
    projectId: 'albertian-wellnest-6f3c5',
    authDomain: 'albertian-wellnest-6f3c5.firebaseapp.com',
    storageBucket: 'albertian-wellnest-6f3c5.firebasestorage.app',
    measurementId: 'G-019FMJ30Y5',
  );
}
